\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS rig_layer_profile (
    id SERIAL PRIMARY KEY,
    project_code VARCHAR(50) NOT NULL,
    machine_code VARCHAR(50) NOT NULL,
    borehole_code VARCHAR(100) NOT NULL,
    layer_index INTEGER NOT NULL,
    layer_id VARCHAR(100) NOT NULL,
    layer_name VARCHAR(255) NOT NULL,
    top_depth_range_m VARCHAR(100),
    top_depth_m DOUBLE PRECISION NOT NULL,
    bottom_depth_m DOUBLE PRECISION NOT NULL,
    thickness_m DOUBLE PRECISION,
    report_thickness_range_m VARCHAR(100),
    report_thickness_representative_m DOUBLE PRECISION,
    top_elevation_range_m VARCHAR(100),
    sample_start INTEGER,
    sample_end INTEGER,
    timestamp_start TIMESTAMP,
    timestamp_end TIMESTAMP,
    engineering_group VARCHAR(255),
    expected_current_a DOUBLE PRECISION,
    expected_torque_knm DOUBLE PRECISION,
    expected_penetration_speed_m_min DOUBLE PRECISION,
    expected_grouting_pressure_mpa DOUBLE PRECISION,
    modeling_description TEXT,
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_code, machine_code, borehole_code, layer_index)
);

CREATE TEMP TABLE rig_layer_profile_import (
    layer_index TEXT,
    layer_id TEXT,
    layer_name TEXT,
    top_depth_range_m TEXT,
    top_depth_m TEXT,
    bottom_depth_m TEXT,
    thickness_m TEXT,
    report_thickness_range_m TEXT,
    report_thickness_representative_m TEXT,
    top_elevation_range_m TEXT,
    sample_start TEXT,
    sample_end TEXT,
    timestamp_start TEXT,
    timestamp_end TEXT,
    engineering_group TEXT,
    expected_current_a TEXT,
    expected_torque_knm TEXT,
    expected_penetration_speed_m_min TEXT,
    expected_grouting_pressure_mpa TEXT,
    modeling_description TEXT
);

\copy rig_layer_profile_import FROM '/home/wyl/projects/soft-soil-ml/data/raw/nbu_west-test/rig001_synthetic_layer_profile_v2.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')

INSERT INTO rig_layer_profile (
    project_code,
    machine_code,
    borehole_code,
    layer_index,
    layer_id,
    layer_name,
    top_depth_range_m,
    top_depth_m,
    bottom_depth_m,
    thickness_m,
    report_thickness_range_m,
    report_thickness_representative_m,
    top_elevation_range_m,
    sample_start,
    sample_end,
    timestamp_start,
    timestamp_end,
    engineering_group,
    expected_current_a,
    expected_torque_knm,
    expected_penetration_speed_m_min,
    expected_grouting_pressure_mpa,
    modeling_description
)
SELECT
    'NBU-WEST-DEMO',
    'RIG-001',
    'BH-001',
    NULLIF(layer_index, '')::integer,
    NULLIF(layer_id, ''),
    NULLIF(layer_name, ''),
    NULLIF(top_depth_range_m, ''),
    NULLIF(top_depth_m, '')::double precision,
    NULLIF(bottom_depth_m, '')::double precision,
    NULLIF(thickness_m, '')::double precision,
    NULLIF(report_thickness_range_m, ''),
    NULLIF(report_thickness_representative_m, '')::double precision,
    NULLIF(top_elevation_range_m, ''),
    NULLIF(sample_start, '')::integer,
    NULLIF(sample_end, '')::integer,
    NULLIF(timestamp_start, '')::timestamp,
    NULLIF(timestamp_end, '')::timestamp,
    NULLIF(engineering_group, ''),
    NULLIF(expected_current_a, '')::double precision,
    NULLIF(expected_torque_knm, '')::double precision,
    NULLIF(expected_penetration_speed_m_min, '')::double precision,
    NULLIF(expected_grouting_pressure_mpa, '')::double precision,
    NULLIF(modeling_description, '')
FROM rig_layer_profile_import
ON CONFLICT (project_code, machine_code, borehole_code, layer_index) DO UPDATE SET
    layer_id = EXCLUDED.layer_id,
    layer_name = EXCLUDED.layer_name,
    top_depth_range_m = EXCLUDED.top_depth_range_m,
    top_depth_m = EXCLUDED.top_depth_m,
    bottom_depth_m = EXCLUDED.bottom_depth_m,
    thickness_m = EXCLUDED.thickness_m,
    report_thickness_range_m = EXCLUDED.report_thickness_range_m,
    report_thickness_representative_m = EXCLUDED.report_thickness_representative_m,
    top_elevation_range_m = EXCLUDED.top_elevation_range_m,
    sample_start = EXCLUDED.sample_start,
    sample_end = EXCLUDED.sample_end,
    timestamp_start = EXCLUDED.timestamp_start,
    timestamp_end = EXCLUDED.timestamp_end,
    engineering_group = EXCLUDED.engineering_group,
    expected_current_a = EXCLUDED.expected_current_a,
    expected_torque_knm = EXCLUDED.expected_torque_knm,
    expected_penetration_speed_m_min = EXCLUDED.expected_penetration_speed_m_min,
    expected_grouting_pressure_mpa = EXCLUDED.expected_grouting_pressure_mpa,
    modeling_description = EXCLUDED.modeling_description,
    imported_at = CURRENT_TIMESTAMP;
